DO $$ BEGIN
 CREATE TYPE "public"."role" AS ENUM('free_agent', 'corrupt_developer', 'influencer', 'detective', 'virus', 'hacker', 'skeptic', 'crazied', 'shared_fate', 'illiterate');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "cornhacks-2025_game" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cornhacks-2025_game_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"status" varchar(50) NOT NULL,
	"current_phase" varchar(50) NOT NULL,
	"start_time" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"end_time" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "cornhacks-2025_player" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cornhacks-2025_player_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"role" "role" NOT NULL,
	"game_id" integer NOT NULL,
	"is_alive" boolean DEFAULT true NOT NULL,
	"is_ai" boolean DEFAULT false NOT NULL,
	"last_action" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "cornhacks-2025_player" ADD CONSTRAINT "cornhacks-2025_player_game_id_cornhacks-2025_game_id_fk" FOREIGN KEY ("game_id") REFERENCES "public"."cornhacks-2025_game"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
